/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:30468326-813c-40d4-8be0-fc3bd4cc18b8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_uJKWnyLEY",
    "aws_user_pools_web_client_id": "1gmhnlipbsiooqfgha6d8uquop",
    "oauth": {}
};


export default awsmobile;
